language: cpp
matrix:
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - sourceline: 'ppa:mhier/libboost-latest'
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - libboost1.67
            - libboost1.67-dev
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - ./autogen.sh
  - ./configure --with-boost-libdir=/usr/lib
  - make dist
  - VERSION=$(head -n 1 configure.ac | cut -d'[' -f3 | cut -d']' -f1)
  - tar -xvzf "trusted-vote-$VERSION.tar.gz"
  - rm -f "trusted-vote-$VERSION.tar.gz"
  - pushd "trusted-vote-$VERSION"
  - ./configure --with-boost-libdir=/usr/lib
  - make
  - make check
  - popd
